### ISSUE TITLE
[Template tags] Including templates

### ISSUE THREAD

**Issue by stdword** [stdword/logseq13-full-house-plugin#17]
reference: https://github.com/stdword/logseq13-full-house-plugin/discussions/18

### If you are waiting for this task:
- Please add 👀 reaction so I can prioritise it over other features
- You can [subscribe](https://stackoverflow.com/questions/14140564/how-to-follow-only-specific-issues-on-github-instead-of-watching-an-entire-proj/14140659#14140659) for notifications on this issue

**Comment by YU000jp** [comment]
Released `@Logseq/libs` v0.0.15 yesterday by @xyhp915
https://github.com/logseq/logseq/pull/8787

![image](https://user-images.githubusercontent.com/111847207/236354191-df8915dd-4a8a-40af-9b84-477241eac1b8.png)
https://github.com/logseq/logseq/blob/a5e31128a6366df002488203406684f78d80c7e3/libs/src/LSPlugin.ts#L449

**Comment by stdword** [comment]
@YU000jp thank you for providing an info about update! 🙏
This is only a part of work for my plugin — I need an ability to include Full House Templates too — it is a bit trickier
