### ISSUE TITLE
Is it possible to use it as a journal template?

### ISSUE THREAD

**Issue by 0w0miki** [stdword/logseq13-full-house-plugin#2]
First, thanks for developing such a cool plugin.

I use page like [[2023/W1]] as periodical retrospective page. For each daily journal, it will have properties like "week" link to this page.

For example, the content of journal 2023-03-19.md should be like:
```markdown
<!-- page properties -->
year:: [[2023]]
week:: [[2023/W12]]

<!-- journal data -->
```

After I see this plugin, I wonder if I can use it to automatically generate my daily journal. For now, I have tried the following thing but fail.
* Create a template like the following:
```
- ## Journal template date
  template:: journal-date
	- year:: ``{ ref(date.from(c.page.name).format('YYYY')) }``
	  week:: ``{ ref(date.from(c.page.name).format('YYYY/[W]w')) }``
```
*  Put the line `{{renderer :template, journal-date}}` in my journal template.

The plugin rendered the macro, so I could not use it to generate my journal.

**Comment by stdword** [comment]
Look at workaround [here](https://github.com/stdword/logseq13-full-house-plugin/blob/main/docs/showcases.md#template-for-an-every-day-journal).
Though it is not so smoothly, but it works 👻

Appropriate feature already is in development roadmap. So you subscribe to notifications on this issue to monitor it ❤️

**Comment by stdword** [comment]
@0w0miki, hi again!

New release of `🏛 Full House Templates` provide a way to use Journal Templates with new `:template-view` command. See details [here](https://github.com/stdword/logseq13-full-house-plugin/blob/main/docs/showcases.md#daily-journal-template).

Hope you enjoy this feature ❤️🙏
