### ISSUE TITLE
[UI] Select template from a list

### ISSUE THREAD

**Issue by bluckholl** [stdword/logseq13-full-house-plugin#23]
Currently when adding full house template command, need to type template name manually.
It will be great if list of templates can be shown, similar to regular templates behavior.

*Current workaround: adding command for each template in config.edn with full render full house template name. (Or using text expander)

Thanks for this great plugin! 🙏

**Comment by stdword** [comment]
Hello! Thanks for the feedback!
I do plan to add the option to choose a template from a list, but first it's important to do some restructuring and add the feature of rendering standard templates with <% %> syntax. I think we can use the current task to keep track of the progress on the «template list» feature. And [this](#24) one for the related.
