### ISSUE TITLE
Render template loss inner block

### ISSUE THREAD

**Issue by CodingXCat** [stdword/logseq13-full-house-plugin#26]
Template with template-including-parent:: true
```
- template:: simple
  template-including-parent:: true
  comment:: The most simple template
	- Hello, Logseq!
		- inner block

Render with
{{renderer :template, simple}}
```
Result
```
- comment:: The most simple template
	- Hello, Logseq!
		- inner block
```

Template without template-including-parent:: true
```
- template:: simple
  comment:: The most simple template
	- Hello, Logseq!
		- inner block
		
Render with
{{renderer :template, simple}}
```
Result
```
- Hello, Logseq!
```

The inner block is missing.

Logseq version : 0.9.15, Plugin version: 3.0.0

**Comment by stdword** [comment]
Reproducible. It's seems to be something has changes in Logseq API. Because inserting blocks code didn't change in v3.0.0

Need some time to gather details

**Comment by CodingXCat** [comment]
https://github.com/logseq/logseq/commit/583a3d5dc8ad7dc4ff5bb14348016fa6b1e901ba
![image](https://github.com/stdword/logseq13-full-house-plugin/assets/1538579/98b16e93-e490-4a6f-a65c-ae5d2bdacf9f)
Does it related with this commit?

**Comment by stdword** [comment]
> Does it related with this commit?
No

This is terrifying, but this is an old bug, not related to Logseq API 😳
Children blocks of **first** block are skipped all the time, even before v3.0.0
How did I not notice this? How did no one notice this? 🙈

Will fix it later today

**Comment by CodingXCat** [comment]
Thanks for offering such a good plugin for us~ 
Really helps a lot in my daily workflow.
