### ISSUE TITLE
How should I use the new syntax

### ISSUE THREAD

**Issue by Gitbreast** [stdword/logseq13-full-house-plugin#28]
I see the new syntax [here](https://stdword.github.io/logseq13-full-house-plugin/#/reference__syntax). But "Use «``[» and «]``» to call" seems not work. I just change the js code base on old template like this.

<img width="588" alt="image" src="https://github.com/stdword/logseq13-full-house-plugin/assets/96460796/6210e40a-84c1-43cf-9a88-ddc3de5b8c77">

**Comment by stdword** [comment]
Works as expected for me:
<img width="600px" src="https://github.com/stdword/logseq13-full-house-plugin/assets/1984175/f113d9a4-6d3d-4631-a597-e2f51d307a95"/>

But NOTE: ``[...]`` need to make a ref to page. To just use a name you need ``...``:
<img width="600px" src="https://github.com/stdword/logseq13-full-house-plugin/assets/1984175/b761a6ad-7341-4297-9e92-ed09a8607e6a"/>

**Comment by Gitbreast** [comment]
Oh my, I check again, it did work. Thanks your detailed example. It’s my mistake — I missed to alter `{}` around an arg in another version with arguments.
