### ISSUE TITLE
Included template renders `template-list-as` property

### ISSUE THREAD

**Issue by croogie** [stdword/logseq13-full-house-plugin#39]
When my template consists of a bunch of `await include('…')` statements, those subtemplates, while rendered, include the `template-list-as` property. 

Desired state: `template-list-as` is being skipped like `template` or `template-including-parent` properties.

**Comment by stdword** [comment]
Both `template-list-as` and `template-usage` are skipping now when `template-including-parent` is turned on.

❗️ The feature will be available in the next release.
