### ISSUE TITLE
Date language

### ISSUE THREAD

**Issue by andrenoboru** [stdword/logseq13-full-house-plugin#40]
I write my notes in `pt-BR`. Is there a configuration to set weekday aliases to be in `pt-BR` instead of `en`? For example, `Terça-feira` instead of `Tuesday`?

Is a setting in the plugin or in Logseq?

**Comment by stdword** [comment]
Just added this feature: it will be automatically based on language in the Logseq's settings.

```
- {{renderer :view, "c.page.day.format('dddd')"}}
- {{renderer :view, "date.from.months()"}}
```

<img width="1172" alt="CleanShot 2024-04-03 at 02 50 49@2x" src="https://github.com/stdword/logseq13-full-house-plugin/assets/1984175/3c89830d-19b7-41a4-bc8a-2ce684b7655c">
<img width="1172" alt="CleanShot 2024-04-03 at 02 50 05@2x" src="https://github.com/stdword/logseq13-full-house-plugin/assets/1984175/0317b971-4509-4b7a-a933-10eb2ac2f888">

However you could manually change locale anywhere with [dayjs method](https://day.js.org/docs/en/i18n/instance-locale):
```
{{renderer :view, "c.page.day.locale('pt-br').format('dddd')"}}
```

❗️ The feature will be available in the next release.
