### ISSUE TITLE
`blocks.uuid()` can not use after updated to v4.3.2

### ISSUE THREAD

**Issue by enel1jk** [stdword/logseq13-full-house-plugin#56]
when use 
```
{{renderer :template, test}}
``` 
to render the [example in doc](https://stdword.github.io/logseq13-full-house-plugin/#/reference__tags_advanced?id=blocks-uuid)
```
- test
  template:: test
	- A ``{ var uuid = blocks.uuid() }``
	- B with ref to A: ``[uuid]``
```

it show this: 
![image](https://github.com/user-attachments/assets/d36407a1-2456-44f4-ab5b-11381d9e617a)

**Comment by enel1jk** [comment]
https://github.com/user-attachments/assets/47c40cdb-b290-4c22-97b9-1f7efb0a4c65

hello
Here is the screen recording. i have been using my template for quite long time after last time ask [this function](https://github.com/stdword/logseq13-full-house-plugin/discussions/45), it work nice, and i have not change my template after that.
my logseq client is up to date(v0.10.9), which hasn't been updated for a long time. I'm not sure if there's any other information you need, please let me know if you need anything. Thank you.
My journal heavily relies on your plugin, please help me.

**Comment by stdword** [comment]
@enel1jk, thank you for opening an issue! 🙏
There is a very huge production only bug, I've missed.
It is fixed now ❤️

**Comment by enel1jk** [comment]
thank you for your great plugin, very useful!
